In [1]:
import numpy as np

NumPy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of NumPy: vectors, arrays, matrices and number generation. Let's start by discussing arrays.

# NumPy Arrays

NumPy arrays are the main way we will use NumPy throughout the course. NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional (1D) arrays and matrices are 2D (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate arrays.

### arange

Return evenly spaced values within a given interval. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
Return evenly spaced numbers over a specified interval. [[reference](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Note that `.linspace()` *includes* the stop value. To obtain an array of common fractions, increase the number of items:</font>

In [15]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye

Creates an identity matrix [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 
Numpy also has lots of ways to create random number arrays:

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [17]:
np.random.rand(2)

array([0.86676672, 0.21740451])

In [18]:
np.random.rand(5,5)

array([[0.25639554, 0.6384497 , 0.18417595, 0.57299404, 0.04949075],
       [0.27321271, 0.27088973, 0.87993011, 0.62073422, 0.13724116],
       [0.40153058, 0.54811571, 0.92742439, 0.28031073, 0.95239183],
       [0.68248139, 0.05351246, 0.66872375, 0.40923086, 0.42539126],
       [0.18124136, 0.97755873, 0.19131618, 0.78147057, 0.0076538 ]])

### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [19]:
np.random.randn(2)

array([-0.99189327, -0.48829654])

In [20]:
np.random.randn(5,5)

array([[ 0.54929649, -0.0454559 , -1.61160833, -0.69550859,  0.21019727],
       [ 0.07565176,  0.28214244,  1.08223463, -0.4736337 , -0.37663751],
       [-0.62787759,  1.53777414, -0.7506695 , -1.35682513,  0.36279357],
       [-0.49156815,  0.40862404,  0.62013499,  1.22478096,  0.103958  ],
       [ 0.35551408, -0.97768542,  0.37382076,  2.39154244, -0.45705735]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [21]:
np.random.randint(1,100)

51

In [22]:
np.random.randint(1,100,10)

array([28, 88, 26, 28, 76, 47, 90, 78, 48, 99])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [23]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [24]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [25]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## Reshape
Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [29]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [30]:
ranarr.max()

39

In [31]:
ranarr.argmax()

7

In [32]:
ranarr.min()

2

In [33]:
ranarr.argmin()

9

## Shape

Shape is an attribute that arrays have (not a method):  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [34]:
# Vector
arr.shape

(25,)

In [35]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [36]:
arr.reshape(1,25).shape

(1, 25)

In [37]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [38]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [39]:
arr.dtype

dtype('int64')

In [40]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

## Create a specific array<a id="2"></a>
<mark>[Return Contents](#0)
<hr>

In actual project engineering, we often need some specific data, and some helper functions are provided in NumPy:

* **zeros:** used to create an array whose elements are all 0
* **ones:** used to create an array whose elements are all 1
* **empty:** used to create uninitialized data. so the content is undefined.
* **arange:** used to create an array by specifying the scope and step-length
* **linespace:** used to create an array by specifying the range and the number of elements
* **random:** used to generate random numbers

In [2]:
a = np.zeros((2,3))
print('np.zeros((2,3)= \n{}\n'.format(a))

b = np.ones((2,3))
print('np.ones((2,3))= \n{}\n'.format(b))

c = np.empty((2,3))
print('np.empty((2,3))= \n{}\n'.format(c))

d = np.arange(1, 2, 0.3)
print('np.arange(1, 2, 0.3)= \n{}\n'.format(d))

e = np.linspace(1, 2, 7)
print('np.linspace(1, 2, 7)= \n{}\n'.format(e))

f = np.random.random((2,3))
print('np.random.random((2,3))= \n{}\n'.format(f))

np.zeros((2,3)= 
[[0. 0. 0.]
 [0. 0. 0.]]

np.ones((2,3))= 
[[1. 1. 1.]
 [1. 1. 1.]]

np.empty((2,3))= 
[[1. 1. 1.]
 [1. 1. 1.]]

np.arange(1, 2, 0.3)= 
[1.  1.3 1.6 1.9]

np.linspace(1, 2, 7)= 
[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.        ]

np.random.random((2,3))= 
[[0.38872141 0.28524791 0.55152161]
 [0.01243239 0.68821491 0.22969776]]



## Shape and operation<a id="3"></a>
<mark>[Return Contents](#0)
<hr>

In addition to generating an array, after we have held some data, we may need to generate some new data structures based on the existing array. In this case, we can use the following functions:

* **reshape:** used to generate a new array based on the existing array and the specified shape
* **vstack:** used to stack multiple arrays in vertical direction (the dimensions of the array must be matched)
* **hstack:** used to stack multiple arrays in horizontal direction (the dimensions of the array must be matched)
* **hsplit:** used to split the array horizontally
* **vsplit:** used to split the array vertically

We'll use some examples to illustrate.

To make it easier to test, let's create a few data:

* **zero_line:** an array with a row containing three 0
* **one_column:** an array with a column containing three 1
* **a:** a matrix with 2 rows and 3 columns
* **b:** an integer array in the interval of [11,20]

In [35]:
zero_line = np.zeros((1,3))
one_column = np.ones((3,1))

a = np.array([(1,2,3), (4,5,6)])
b = np.arange(11, 20)

print("zero_line = \n{}\n".format(zero_line))
print("one_column = \n{}\n".format(one_column))
print("a = \n{}\n".format(a))
print("b = \n{}\n".format(b))

zero_line = 
[[0. 0. 0.]]

one_column = 
[[1.]
 [1.]
 [1.]]

a = 
[[1 2 3]
 [4 5 6]]

b = 
[11 12 13 14 15 16 17 18 19]



In [7]:
print(a.shape, b.shape)

(3, 2) (3, 3)


In [14]:
print(zero_line.shape, one_column.shape)

(1, 3) (3, 1)


In [36]:
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
b.shape

(9,)

In [18]:
b = b.reshape(3, -1)
b.shape

(3, 3)

In [19]:
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [10]:
a = a.reshape(3, 2)
a.shape

(3, 2)

In [16]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
one_column

array([[1.],
       [1.],
       [1.]])

In [12]:

d = np.hstack((a, b, one_column))
d

array([[ 1.,  2., 11., 12., 13.,  1.],
       [ 3.,  4., 14., 15., 16.,  1.],
       [ 5.,  6., 17., 18., 19.,  1.]])

In [15]:
d.shape

(3, 6)

In [34]:
v = np.vstack((a, b))
v


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [22]:
e = np.hsplit(d, 3) # Split a into 3

e

[array([[1., 2.],
        [3., 4.],
        [5., 6.]]),
 array([[11., 12.],
        [14., 15.],
        [17., 18.]]),
 array([[13.,  1.],
        [16.,  1.],
        [19.,  1.]])]

In [23]:
e[0]

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [24]:
e[1]

array([[11., 12.],
       [14., 15.],
       [17., 18.]])

In [25]:
e[2]

array([[13.,  1.],
       [16.,  1.],
       [19.,  1.]])

In addition to specifying number to split the array evenly, we can also specify the number of columns to split. The following is to split the array d from the first column and the third column:

In [32]:
f = np.hsplit(d, (1, 3)) # # Split a after the 1st and the 3rd column
f

[array([[1.],
        [3.],
        [5.]]),
 array([[ 2., 11.],
        [ 4., 14.],
        [ 6., 17.]]),
 array([[12., 13.,  1.],
        [15., 16.,  1.],
        [18., 19.,  1.]])]

In [33]:
g = np.vsplit(d, 3)
g

[array([[ 1.,  2., 11., 12., 13.,  1.]]),
 array([[ 3.,  4., 14., 15., 16.,  1.]]),
 array([[ 5.,  6., 17., 18., 19.,  1.]])]

# Great Job!